config/routes.rb
Rails.application.routes.draw do
  get 'fdss_api_keys/index'
  get 'fds_context_menu/files_operation'
  get 'home/index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  # get "up" => "rails/health#show", as: :rails_health_check

  post "upload_file", to: "upload_files#create_file"

  get "file_explore", to: "file_manager#file_explore", as: "file_explore"
  post "create_dir", to: "file_manager#create_dir", as: "create_dir"
  post "delete_nodes", to: "file_manager#delete_nodes", as: "delete_nodes"
  post "move_nodes", to: "file_manager#move_nodes", as: "move_nodes"
  post "copy_nodes", to: "file_manager#copy_nodes", as: "copy_nodes"
  post "re_name", to: "file_manager#re_name", as: "re_name"
  get "direct_download", to: "file_manager#direct_download", as: "direct_download"
  post "get_detail", to:"file_manager#get_detail", as: "get_detail"

  post "select_target_dir", to: "file_manager#select_target_dir", as: "dir_node_info"

  # Fdss API
  post "get_all_node_ids", to: "fdss_sync_manager#all_node_ids_without_root", as: "get_all_node_ids"
  post "get_nodes_info", to: "fdss_sync_manager#get_nodes_info_by_ids", as: "get_nodes_info"
  post "get_root_info", to: "fdss_sync_manager#get_root_info", as: "get_root_info"
  get "fdss_download", to: "fdss_sync_manager#fdss_download", as: "fdss_download"


  # Defines the root path route ("/")
  root "home#index"

  # devise_for :users

  Rails.application.routes.draw do
  get 'fdss_api_keys/index'
    devise_for :users, controllers: {
      registrations: 'users/registrations'
    }
  end

  get "system_settings", to:"settings#system_settings", as: "system_settings"
  get "user_settings", to:"settings#user_settings", as:"user_settings"

  post "fdss_api_key_create", to: "fdss_api_keys#create", as: "fdss_api_key_create"
  post "fdss_api_key_destroy", to: "fdss_api_keys#destroy", as: "fdss_api_key_destroy"
  get "fdss_api_key_detail", to: "fdss_api_keys#detail", as: "fdss_api_key_detail"
end

app/controllers/file_manager_controller.rb
class FileManagerController < ApplicationController
  before_action :only_lan_host_allow, only: :direct_download

  def dump_params
    puts "===============PARAMS=================="
    if params.present?
      puts "get source params = #{params}"
      params.each_key do |key|
        puts "get param #{key} = #{params[key]}"
      end
    end
    puts "======================================"
  end

  def dump_headers
    puts "==============HEADERS================="
    request.headers.each do |key, value|
      # 在这里处理每个头部信息的键和值
      puts "#{key}: #{value}"
    end
    puts "======================================"
  end

  def dump_user
    puts "==============USER===================="
    puts "current user = #{current_user.email}"
    puts "======================================"
  end

  before_action :dump_params
  # before_action :dump_headers
  before_action :dump_user

  def file_explore
    puts "current user = #{current_user}"
    dir_path_str = params[:dir]
    sort_str = params[:sort]


    @dir_node = FdsNode.find_by_node_path_str(dir_path_str)
    @dir_node = FdsNode.root unless @dir_node
    @sub_nodes = @dir_node.sub_nodes.order(node_type: :desc)
    if sort_str.present?
      sorts = sort_str.split(",");
      sorts.each do |sort|
        f = sort.split(":")[0]
        v = sort.split(":")[1]
        order_str = "#{f} #{v}"
        @sub_nodes = @sub_nodes.order(order_str)
      end
    end
  end

  def create_dir
    dir_path_str = params[:dir]
    dir_name = params[:dir_name]

    FdsNode.transaction do
      begin
        @dir_node = FdsNode.find_by_node_path_str!(dir_path_str)
        new_node = FdsNode.new(parent_node: @dir_node, node_type: FdsNode.DIR_TYPE, name: dir_name, size: 0)
        new_node.save!

        fds_storage_path = Rails.application.config.fds.storage_path
        aim_path = File.join(fds_storage_path, dir_path_str)
        aim_path = File.join(aim_path, dir_name)
        FileUtils.mkdir_p(aim_path)

        flash[:success] = "执行成功"
        redirect_to request.referrer
      rescue ActiveRecord::RecordInvalid, ActiveRecord::RecordNotFound, RuntimeError, Errno::ENAMETOOLONG, Errno::EACCES => e
        flash[:danger] = e.message
        redirect_to request.referrer
        raise ActiveRecord::Rollback
      end
    end
  end

  def delete_nodes
    ids = params[:ids]
    result = true
    nodes = FdsNode.where(id: ids)
    fds_storage_path = Rails.application.config.fds.storage_path
    nodes.each do |node|
      FdsNode.transaction do
        begin
          node_path = File.join(fds_storage_path, node.node_path_str)
          node.destroy!
          FileUtils.rm_rf(node_path) if File.exist?(node_path)
        rescue ActiveRecord::RecordInvalid, ActiveRecord::RecordNotFound, RuntimeError, Errno::EISDIR, Errno::EACCES, Errno::ENOENT, Errno::EINVAL => e
          result = false
          puts "#{e.message}"
          raise ActiveRecord::Rollback
        end
      end
    end
    if result
      flash[:success] = "操作成功"
      redirect_to request.referrer
    else
      flash[:danger] = "操作失败"
      redirect_to request.referrer
    end
  end

  def select_target_dir
    ret = {}
    node_id = params[:target_node_id]
    node = FdsNode.find_by(id: node_id)
    if node && node.node_type == FdsNode.DIR_TYPE
      ret[:ret_code] = 0
      ret[:err_msg] = ""
      ret[:data] = {}
      ret[:data][:node] = { id: node.id, name: node.name, node_path_str: node.node_path_str, node_path: node.node_path.map { |node| { id: node.id, name: node.name } } }
      sub_dirs = node.sub_nodes.select { |node| node.node_type == FdsNode.DIR_TYPE }
      ret[:data][:sub_dir_nodes] = sub_dirs.map { |node| { id: node.id, name: node.name } }
    else
      ret[:ret_code] = -1
      ret[:err_msg] = "目录不存在"
      ret[:data] = {}
    end
    render json: ret
  end

  def move_nodes
    ids = JSON.parse(params[:ids])
    target_id = params[:target_id]

    result = true

    fds_storage_path = Rails.application.config.fds.storage_path

    begin
      target_node = FdsNode.find(target_id)
      target_path = File.join(fds_storage_path, target_node.node_path_str)
    rescue ActiveRecord::RecordNotFound => e
      flash[:danger] = "操作失败"
      redirect_to request.referrer
      return
    end

    nodes = FdsNode.where(id: ids)
    nodes.each do |node|
      FdsNode.transaction do
        begin
          node_path = File.join(fds_storage_path, node.node_path_str)
          node.update!(parent_node: target_node)
          FileUtils.mv(node_path, target_path)
        rescue ActiveRecord::RecordInvalid, ActiveRecord::RecordNotFound, RuntimeError, Errno::EISDIR, Errno::EACCES, Errno::ENOENT, Errno::EEXIST, Errno::EINVAL => e
          result = false
          puts "#{e.message}"
          raise ActiveRecord::Rollback
        end
      end
    end

    if result
      flash[:success] = "操作成功"
      # redirect_to file_explore_path(dir: target_node.node_path_str)
      redirect_to request.referrer
    else
      flash[:danger] = "操作失败"
      redirect_to request.referrer
    end

  end

  def copy_nodes
    ids = params[:ids].map(&:to_i)
    target_id = params[:target_id].to_i
    ret = {}
    result = true

    fds_storage_path = Rails.application.config.fds.storage_path

    begin
      target_node = FdsNode.find(target_id)
      target_path = File.join(fds_storage_path, target_node.node_path_str)
    rescue ActiveRecord::RecordNotFound => e
      flash[:danger] = "操作失败"
      ret[:ret_code] = -1
      ret[:err_msg] = "操作失败"
      ret[:data] = {}
      render json: ret
      return
    end

    nodes = FdsNode.where(id: ids)
    nodes.each do |node|
      FdsNode.transaction do
        begin
          node_path = File.join(fds_storage_path, node.node_path_str)
          FdsNode.copy_node(node, target_node)
          FileUtils.cp_r(node_path, target_path)
        rescue ActiveRecord::RecordInvalid, ActiveRecord::RecordNotFound, RuntimeError, Errno::EISDIR, Errno::EACCES, Errno::ENOENT, Errno::EEXIST, Errno::EINVAL => e
          result = false
          puts "#{e.message}"
          raise ActiveRecord::Rollback
        end
      end
    end

    if result
      flash[:success] = "操作成功"
      ret[:ret_code] = 0
      ret[:err_msg] = ""
      ret[:data] = {}
    else
      flash[:danger] = "操作失败"
      ret[:ret_code] = -1
      ret[:err_msg] = "操作失败"
      ret[:data] = {}
    end

    render json: ret
  end

  def re_name
    ids = JSON.parse(params[:ids])
    new_name = params[:new_name]

    fds_storage_path = Rails.application.config.fds.storage_path
    FdsNode.transaction do
      begin
        id = ids.first
        node = FdsNode.find(id)
        node_path = File.join(fds_storage_path, node.node_path_str)
        node.update!(name: new_name)

        new_node_path = File.join(fds_storage_path, node.node_path_str)
        File.rename(node_path, new_node_path)

        flash[:success] = "操作成功"
        redirect_to request.referrer
      rescue ActiveRecord::RecordInvalid, ActiveRecord::RecordNotFound, RuntimeError, Errno::EISDIR, Errno::EACCES, Errno::ENOENT, Errno::EEXIST, Errno::EINVAL, Errno::ENOTEMPTY => e
        flash[:danger] = "操作失败"
        puts "#{e.message}"
        redirect_to request.referrer
        raise ActiveRecord::Rollback
      end
    end
  end

  def direct_download
    id = params[:id]
    fds_storage_path = Rails.application.config.fds.storage_path
    begin
      node = FdsNode.find(id)
      node_path = File.join(fds_storage_path, node.node_path_str)
      send_file node_path, disposition: 'attachment', stream: 'true', buffer_size: '4096'
    rescue  ActiveRecord::RecordInvalid, ActiveRecord::RecordNotFound, RuntimeError, Errno::EISDIR, Errno::EACCES, Errno::ENOENT, Errno::EEXIST, Errno::EINVAL, Errno::ENOTEMPTY,ActionController::MissingFile => e
      flash[:danger] = "下载失败"
      redirect_to request.referrer
    end
  end

  def get_detail
    id = params[:id]
    wan_address = Rails.application.config.fds.wan_address
    ret = {}
    ret[:data] = []

    begin
      node = FdsNode.find(id)
      ret[:ret_code] = 0
      ret[:err_msg] = ""
      if node.node_type == FdsNode.FILE_TYPE
        ret[:data].push({"文件名": node.name})
        ret[:data].push({"大小": node.human_size})
        ret[:data].push({"创建日期": node.human_created_at})
        ret[:data].push({"修改日期": node.human_updated_at})
        ret[:data].push({"文件MD5": node.md5})
        if wan_address.end_with?("/")
          download_url = "#{wan_address}direct_download?id=#{node.id}"
        else
          download_url = "#{wan_address}/direct_download?id=#{node.id}"
        end
        ret[:data].push({"下载链接": download_url})
      else
        ret[:data].push({"目录名": node.name})
        ret[:data].push({"大小": node.human_size})
        ret[:data].push({"创建日期": node.human_created_at})
        ret[:data].push({"修改日期": node.human_updated_at})
      end
    rescue  ActiveRecord::RecordNotFound => e
      ret[:ret_code] = -1
      ret[:err_msg] = "文件或目录不存在!!!"
    end

    render json: ret
  end

end

app/helpers/file_manager_helper.rb
module FileManagerHelper
end

app/views/file_manager/_file_list.html.erb
<%= render_upload_file(@dir_node.node_path_str) %>

<style>
    .node-selected {
        background-color: #b1baff;
    }

    .link-wrapper {
        display: flex;
        text-decoration: none;
        align-items: center;
        color: black;
    }

    .link-wrapper img {
        width: 32px;
        height: 32px;
        flex: 1;
    }

    .link-wrapper span {
        flex: 20;
        width: 100%;
        height: 100%;
    }

    .link-dots {
        color: black;
        text-decoration: none;
    }

    .link-dots:hover {
        color: black;
        font-weight: bold;
    }

    .table-head-link {
        color: black;
        text-decoration: none;
    }
</style>

<div>
  <table class="table table-hover" func="files_list">
    <colgroup>
      <col style="width: 2%;">
      <col style="width: 70%;">
      <col style="width: 5%">
      <col style="width: 8%;">
      <col style="width: 15%;">
    </colgroup>
    <thead>
    <tr>
      <th><input type="checkbox" id="toggle_check_box" onclick="toggle_check_boxes(this)"></th>
      <th onclick="choose_sort_param('name')">
        <a href="javascript: void(0)" class="table-head-link">
          文件名
            <span>
              <img src="<%= asset_path("asc_icon") %>" id="name_asc" style="display: none">
              <img src="<%= asset_path("desc_icon") %>" id="name_desc" style="display: none">
            </span>
        </a>

      </th>
      <th></th>
      <th onclick="choose_sort_param('size')">
        <a href="javascript: void(0)" class="table-head-link">
        文件大小
        <span>
          <img src="<%= asset_path("asc_icon") %>" id="size_asc" style="display: none">
          <img src="<%= asset_path("desc_icon") %>" id="size_desc" style="display: none">
        </span>
        </a>
      </th>
      <th onclick="choose_sort_param('updated_at')">
        <a href="javascript: void(0)" class="table-head-link">
        修改日期
        <span>
          <img src="<%= asset_path("asc_icon") %>" id="updated_at_asc" style="display: none">
          <img src="<%= asset_path("desc_icon") %>" id="updated_at_desc" style="display: none">
        </span>
        </a>
      </th>
    </tr>
    </thead>
    <tbody>
    <% @sub_nodes.each do |node| %>
      <tr id=<%= "tr-#{node.id}" %> oncontextmenu="tr_context_menu(this)">
        <td style="vertical-align: middle; text-align: center">
          <input type="checkbox" id="<%= node.id %>" onclick="select_check_box(this)">
        </td>

        <% if node.node_type == FdsNode.DIR_TYPE %>
          <td>
            <a class="link-wrapper" href="<%= file_explore_path(dir: node.node_path_str) %>">
              <%= image_tag "#{node.node_type_str}_icon.svg" %>
              <span><%= node.name %></span>
            </a>
          </td>
        <% else %>
          <td>
            <a class="link-wrapper" href="<%= direct_download_path(id: node.id) %>">
              <%= image_tag "#{node.node_type_str}_icon.svg" %>
              <span><%= node.name %></span>
            </a>
          </td>
        <% end %>

        <td style="vertical-align: middle" onclick="tr_context_menu(this.parentNode)">
          <a class="link-dots" href="javascript:void(0)" >&#x22EF</a>
        </td>
        <td style="vertical-align: middle;"><%= node.human_size %></td>
        <td style="vertical-align: middle;"><%= node.human_updated_at %></td>
      </tr>
    <% end %>

    </tbody>
  </table>
</div>

<ul class="dropdown-menu" id="contextMenu">
</ul>

<script>
  $(document).ready(update_sort_icon)

  // 针对排序
  function update_sort_icon(){
      // 获取当前网页的 URL
      let url = new URL(window.location.href);
      let params = new URLSearchParams(url.search);
      let sort_str = params.get('sort');

      if (sort_str !== null && sort_str !== ""){
          first_sort = sort_str_to_obj(sort_str)[0];
          let f = first_sort["f"];
          let v = first_sort["v"];
          let node_id = `${f}_${v}`;
          let icon = document.getElementById(node_id);
          icon.style.display = "";
      }
  }

  function sort_str_to_obj(sort_str) {
    let sorts = [];
    if (sort_str === null){
        return sorts;
    }
    let sort_strs = sort_str.split(",");
    for (let i = 0; i < sort_strs.length; i++){
        sorts.push({"f": sort_strs[i].split(":")[0], "v": sort_strs[i].split(":")[1] })
    }
    return sorts;
  }

  function sort_obj_to_str(sort_obj) {
    let result_str = '';
    if (sort_obj === null){
        return result_str;
    }
    for (let i = 0; i < sort_obj.length; i++){
        if (i === 0){
            result_str = `${sort_obj[i]["f"]}:${sort_obj[i]["v"]}`
        }else{
            result_str = `${result_str},${sort_obj[i]["f"]}:${sort_obj[i]["v"]}`
        }
    }
    return result_str
  }
  
  function choose_sort_param(field) {
      // 获取当前网页的 URL
      var url = new URL(window.location.href);

      // 创建一个 URLSearchParams 对象
      var params = new URLSearchParams(url.search);
      let sort_str = params.get('sort');

      let sort_obj = sort_str_to_obj(sort_str);
      let value_set = false;
      for(let i = 0 ; i < sort_obj.length; i++){
          let f = sort_obj[i]["f"];
          if (field === f){
              sort_obj[i]["v"] = sort_obj[i]["v"]==="asc"? "desc":"asc";
              let item = sort_obj.splice(i,1)[0];
              sort_obj.unshift(item)
              value_set = true;
              break;
          }
      }
      if (!value_set){
          sort_obj.unshift({"f" : field, "v": "asc" });
      }
      let new_sort_str = sort_obj_to_str(sort_obj);
      params.set('sort', new_sort_str);
      url.search = params.toString();
      window.location.href = url.toString();
  }


    // 针对 check_box 的操作
    function select_check_box(check_box) {
        var tr = check_box.parentNode.parentNode;
        if (check_box.checked) {
            tr.className = "node-selected";
        } else {
            tr.className = "";
        }
    }

    function toggle_check_boxes(toggle_check_box) {
        var check_boxes = document.querySelectorAll('table[func="files_list"] tbody input[type="checkbox"]');
        if (toggle_check_box.checked) {
            for (var i = 0; i < check_boxes.length; i++) {
                check_boxes[i].checked = true;
                select_check_box(check_boxes[i])
            }
        } else {
            for (var i = 0; i < check_boxes.length; i++) {
                check_boxes[i].checked = false;
                select_check_box(check_boxes[i])
            }
        }
    }

    // 针对 TR 的操作
    function cancel_other_checkbox() {
        var check_boxes = document.querySelectorAll('table[func="files_list"] tbody input[type="checkbox"]');
        for (var i = 0; i < check_boxes.length; i++) {
            check_boxes[i].checked = false;
            select_check_box(check_boxes[i]);
        }
    }

    function selected_ids() {
        let selected_ids = []
        let check_boxes = document.querySelectorAll('table[func="files_list"] tbody input[type="checkbox"]');
        for (var i = 0; i < check_boxes.length; i++) {
            if (check_boxes[i].checked) {
                selected_ids.push(parseInt(check_boxes[i].id))
            }
        }
        return selected_ids;
    }

    function tr_context_menu(tr) {
        event.preventDefault();
        let x = event.pageX;
        let y = event.pageY;

        let checkbox = tr.querySelector('input[type="checkbox"]');
        if (!checkbox.checked) {
            cancel_other_checkbox();
            checkbox.checked = true;
            select_check_box(checkbox);
        }
        let s_ids = selected_ids();

        $.ajax({
            type: "get",
            url: "<%= fds_context_menu_files_operation_path %>",
            data: {ids: s_ids},
            success: function (response) {
                let ul = document.getElementById("contextMenu");
                ul.style.left = x + "px";
                ul.style.top = y + "px";
                ul.style.display = "block";
                ul.innerHTML = "";
                ul.innerHTML = response;

            },
            error: function () {
            }
        });

        $(document).on("click", function(event) {
            $("#contextMenu").hide();
        });
    }

</script>

app/views/file_manager/_file_path_nav.html.erb
<% node_path = @dir_node.node_path %>
<% node_path.pop %>

<div>

  <div class="row">
    <div class="col d-flex align-items-center">
      <nav style="--bs-breadcrumb-divider: '>';" aria-label="breadcrumb">
        <ol class="breadcrumb">

          <% if node_path.present? %>
            <%= puts "node_path debug #{node_path}" %>
            <% node_path.each do |node| %>
              <li class="breadcrumb-item">
                <a href="<%= file_explore_path(dir: node.node_path_str) %>" %><%= node.name %></a></li>
            <% end %>
          <% end %>
          <li class="breadcrumb-item active" aria-current="page"><%= @dir_node.name %></li>
        </ol>
      </nav>
    </div>
    <div class="col d-flex justify-content-end">
      <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#create_dir">创建目录</button>
    </div>
  </div>

</div>

<div class="modal fade" id="create_dir" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h1 class="modal-title fs-5" id="exampleModalLabel">创建新目录</h1>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <%= form_tag create_dir_path, method: :post do %>
        <div class="modal-body">
          <div class="mb-3">
            <label for="recipient-name" class="col-form-label">目录名称:</label>
            <input type="text" class="form-control" id="recipient-name" name="dir_name">
          </div>
        </div>
        <%= hidden_field_tag(:dir, @dir_node.node_path_str) %>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">取消</button>
          <button type="submit" class="btn btn-primary">确认</button>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/file_manager/_move_node_modal.html.erb
<div class="modal fade" id="move_nodes_modal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered modal-dialog-scrollable">
    <div class="modal-content">
      <div class="modal-header">
        <h1 class="modal-title fs-5" id="exampleModalScrollableTitle">选择目录</h1>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>

      <div class="modal-body" id="target_node_select">

        <div id="target_node_page">
          <div class="col d-flex align-items-center">
            <nav style="--bs-breadcrumb-divider: '>';" aria-label="breadcrumb">
              <ol class="breadcrumb" id="target_node_nav">
              </ol>
            </nav>
          </div>

          <table class="table table-hover">
            <colgroup>
              <col style="width: 100%;">
            </colgroup>
            <thead>
            <tr>
              <th>目录名</th>
            </tr>
            </thead>
            <tbody id="target_node_content">
            </tbody>
          </table>
        </div>

      </div>

      <div class="container" id="target_node_error" style="display: none">
        <div class="alert alert-danger" role="alert">
          请求失败!!!
        </div>
      </div>

      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">取消</button>
        <%= form_tag move_nodes_path, method: :post, id: "move_nodes_form" do %>
        <% end %>
        <div id="copy_nodes_div"></div>
      </div>

    </div>
  </div>
</div>


<div class="modal fade" id="error_copy_dialog" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h1 class="modal-title fs-5" id="exampleModalLabel">提示：</h1>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        请求失败！！！
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">关闭</button>
      </div>
    </div>
  </div>
</div>

<script>
    var main_node_id = <%= @dir_node.id %>;
    $(document).ready(function () {
        $("#move_nodes_modal").on("show.bs.modal", function () {
            console.log("展示");
            show_target_dialog(main_node_id);
        });
        $("#move_nodes_modal").on("hide.bs.modal", function () {
            console.log("隐藏");
        });
    })


    function show_target_dialog(node_id) {
        let page_div = document.getElementById("target_node_page")
        let error_div = document.getElementById("target_node_error")
        $.ajax({
            type: "post",
            url: "<%= dir_node_info_path %>",
            data: {target_node_id: node_id},
            success: function (response) {
                console.log(response)
                if (response["ret_code"] !== 0) {
                    clear_all_content()
                    error_div.style = ""
                    page_div.style = "display: none"
                    return -1;
                }
                error_div.style = "display: none"
                page_div.style = ""
                draw_target_node_nav(response)
                draw_target_node_content(response)
                draw_move_form_info(selected_ids(),node_id)
                draw_copy_info(selected_ids(),node_id)
            },
            error: function (response) {
                clear_all_content()
                error_div.style = ""
                page_div.style = "display: none"
            }
        })
    }

    function clear_all_content() {
        let page_nav_div = document.getElementById("target_node_nav");
        page_nav_div.innerHTML = "";
        let page_content_div = document.getElementById("target_node_content");
        page_content_div.innerHTML = "";
        let move_nodes_form = document.getElementById("move_nodes_form");
        move_nodes_form.innerHTML = "";
    }

    function draw_target_node_nav(response) {
        let page_nav_div = document.getElementById("target_node_nav");
        page_nav_div.innerHTML = "";
        node_path = response["data"]["node"]["node_path"]
        for (let i = 0; i < node_path.length; i++) {
            if (i + 1 === node_path.length) {
                page_nav_div.innerHTML += `<li class="breadcrumb-item active" aria-current="page">${node_path[i]["name"]}</li>`
            } else {
                page_nav_div.innerHTML += `<li class="breadcrumb-item">
                     <a href="javascript: void(0)" onclick="show_target_dialog(${node_path[i]["id"]})" %>${node_path[i]["name"]}</a>
                    </li>`
            }
        }
    }

    function draw_target_node_content(response) {
        let page_content_div = document.getElementById("target_node_content");
        page_content_div.innerHTML = "";
        sub_dir_nodes = response["data"]["sub_dir_nodes"]
        for (let i = 0; i < sub_dir_nodes.length; i++) {
            page_content_div.innerHTML += `<tr>
            <td>
              <a class="link-wrapper" href="javascript: void(0)" onclick="show_target_dialog(${sub_dir_nodes[i]["id"]})">
                <%= image_tag "dir_icon.svg" %>
                <span>${sub_dir_nodes[i]["name"]}</span>
              </a>
            </td>
          </tr>`
        }
    }

    function draw_move_form_info(ids, target_id) {
        let move_nodes_form = document.getElementById("move_nodes_form");
        move_nodes_form.innerHTML = ""

        let ids_field = document.createElement("input");
        ids_field.type = "hidden";
        ids_field.name = "ids";
        ids_field.value = JSON.stringify(ids);

        let target_id_field = document.createElement("input");
        target_id_field.type = "hidden";
        target_id_field.name = "target_id";
        target_id_field.value = target_id;

        let submit_button = document.createElement("button");
        submit_button.type = "submit";
        submit_button.className = "btn btn-primary";
        submit_button.textContent = "移动";

        move_nodes_form.appendChild(ids_field);
        move_nodes_form.appendChild(target_id_field);
        move_nodes_form.appendChild(submit_button);
    }

    function draw_copy_info(ids, target_id) {
        let move_nodes_div = document.getElementById("copy_nodes_div");
        move_nodes_div.innerHTML = "";

        let copy_button = document.createElement("button")
        copy_button.className = "btn btn-primary";
        copy_button.textContent = "复制";

        copy_button.addEventListener("click", function () {
            console.log("开始拷贝")
            $.ajax({
                type: "post",
                url: "<%= copy_nodes_path %>",
                data: {ids: ids, target_id: target_id},
                success: function (response) {
                    console.log("成功")
                    console.log(response)
                    location.reload();
                },
                error: function (response) {
                    console.log("失败")
                    console.log(response)
                    let modal = document.getElementById("error_copy_dialog");
                    let modalInstance = new bootstrap.Modal(modal);
                    modalInstance.show();
                }
            })
        })


        move_nodes_div.appendChild(copy_button);

    }


</script>

app/views/file_manager/file_explore.html.erb
<%= render "file_path_nav" %>
<%= render "file_list" %>
<%= render "move_node_modal" %>
<%= render "rename_modal" %>
<%= render "detail_modal" %>