config/routes.rb
Rails.application.routes.draw do
  get 'fdss_api_keys/index'
  get 'fds_context_menu/files_operation'
  get 'home/index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  # get "up" => "rails/health#show", as: :rails_health_check

  post "upload_file", to: "upload_files#create_file"

  get "file_explore", to: "file_manager#file_explore", as: "file_explore"
  post "create_dir", to: "file_manager#create_dir", as: "create_dir"
  post "delete_nodes", to: "file_manager#delete_nodes", as: "delete_nodes"
  post "move_nodes", to: "file_manager#move_nodes", as: "move_nodes"
  post "copy_nodes", to: "file_manager#copy_nodes", as: "copy_nodes"
  post "re_name", to: "file_manager#re_name", as: "re_name"
  get "direct_download", to: "file_manager#direct_download", as: "direct_download"
  post "get_detail", to:"file_manager#get_detail", as: "get_detail"

  post "select_target_dir", to: "file_manager#select_target_dir", as: "dir_node_info"

  # Fdss API
  post "get_all_node_ids", to: "fdss_sync_manager#all_node_ids_without_root", as: "get_all_node_ids"
  post "get_nodes_info", to: "fdss_sync_manager#get_nodes_info_by_ids", as: "get_nodes_info"
  post "get_root_info", to: "fdss_sync_manager#get_root_info", as: "get_root_info"
  get "fdss_download", to: "fdss_sync_manager#fdss_download", as: "fdss_download"


  # Defines the root path route ("/")
  root "home#index"

  # devise_for :users

  Rails.application.routes.draw do
  get 'fdss_api_keys/index'
    devise_for :users, controllers: {
      registrations: 'users/registrations'
    }
  end

  get "system_settings", to:"settings#system_settings", as: "system_settings"
  get "user_settings", to:"settings#user_settings", as:"user_settings"

  post "fdss_api_key_create", to: "fdss_api_keys#create", as: "fdss_api_key_create"
  post "fdss_api_key_destroy", to: "fdss_api_keys#destroy", as: "fdss_api_key_destroy"
  get "fdss_api_key_detail", to: "fdss_api_keys#detail", as: "fdss_api_key_detail"
end

app/controllers/settings_controller.rb
class SettingsController < ApplicationController

  def system_settings
    @tabs = {system_config: "系统配置", api_manager: "API访问", user_manager: "用户管理"}
    @path_method = "system_settings_path"
    @fdss_api_keys = FdssApiKey.all
  end

  def user_settings

  end
end

app/helpers/settings_helper.rb
module SettingsHelper
end

app/views/settings/_api_manager.html.erb
<br>

<h3>Fdss Api 管理</h3>

<div style="text-align: right">
  <%= link_to "添加密钥", fdss_api_key_create_path, class: "btn btn-primary", method: :post %>
</div>

<% if @fdss_api_keys.present? %>
  <table class="table table-hover">
    <thead>
    <tr>
      <th scope="col">Fdss 序列号</th>
      <th scope="col"></th>
    </tr>
    </thead>

    <tbody>
    <% @fdss_api_keys.each do |fdss_api_key| %>
      <tr>
        <td style="vertical-align: middle"><%= fdss_api_key.serial %></td>
        <td style="text-align: right">
          <div class="btn-group" role="group" aria-label="Basic mixed styles example">
            <button class="btn btn-success" onclick="show_key_info(<%= fdss_api_key.id %>)">查看密钥</button>
            <%= link_to "删除密钥", fdss_api_key_destroy_path(id: fdss_api_key.id), class: "btn btn-danger", method: :post, data: { confirm: '确定要删除吗？' } %>
          </div>
        </td>
      </tr>
    <% end %>

    </tbody>
  </table>
<% else %>
  <br>
  <div class="alert alert-warning" role="alert">
    没有任何数据
  </div>
<% end %>

  <div class="modal fade" id="fdss_api_key_detail" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered modal-dialog-scrollable">
      <div class="modal-content">
        <div class="modal-header">
          <h1 class="modal-title fs-5" id="exampleModalLabel">密钥信息</h1>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
          <div class="mb-3" id="key_detail_content">
          </div>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-primary" data-bs-dismiss="modal">确认</button>
        </div>
      </div>
    </div>
  </div>

  <script>
      function show_key_info(id) {
          console.log(`show id = ${id}`)

          let detail_content_div = document.getElementById("key_detail_content");
          detail_content_div.innerHTML = ""
          $.ajax({
              method: "get",
              url: "<%= fdss_api_key_detail_path %>",
              data: {id: id},
              success: function (response) {
                  detail_content_div.innerHTML = response
              },
              error: function (response) {
                  detail_content_div.innerHTML = `<div class="alert alert-danger" role="alert">
                                                    请求失败!!!
                                                  </div>`
              }
          })

          let modal = document.getElementById('fdss_api_key_detail');
          let bs_modal = new bootstrap.Modal(modal);
          bs_modal.show();
      }
  </script>

app/views/settings/_system_config.html.erb
<h3>system config</h3>

app/views/settings/_user_manager.html.erb
<h3>user manager</h3>

app/views/settings/system_settings.html.erb
<h2>系统管理</h2>
<br>
<%= render_tabs %>


<%= render @tab.to_s %>

app/views/settings/user_settings.html.erb
<h1>用户配置</h1>