config/routes.rb
Rails.application.routes.draw do
  get 'fdss_api_keys/index'
  get 'fds_context_menu/files_operation'
  get 'home/index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  # get "up" => "rails/health#show", as: :rails_health_check

  post "upload_file", to: "upload_files#create_file"

  get "file_explore", to: "file_manager#file_explore", as: "file_explore"
  post "create_dir", to: "file_manager#create_dir", as: "create_dir"
  post "delete_nodes", to: "file_manager#delete_nodes", as: "delete_nodes"
  post "move_nodes", to: "file_manager#move_nodes", as: "move_nodes"
  post "copy_nodes", to: "file_manager#copy_nodes", as: "copy_nodes"
  post "re_name", to: "file_manager#re_name", as: "re_name"
  get "direct_download", to: "file_manager#direct_download", as: "direct_download"
  post "get_detail", to:"file_manager#get_detail", as: "get_detail"

  post "select_target_dir", to: "file_manager#select_target_dir", as: "dir_node_info"

  # Fdss API
  post "get_all_node_ids", to: "fdss_sync_manager#all_node_ids_without_root", as: "get_all_node_ids"
  post "get_nodes_info", to: "fdss_sync_manager#get_nodes_info_by_ids", as: "get_nodes_info"
  post "get_root_info", to: "fdss_sync_manager#get_root_info", as: "get_root_info"
  get "fdss_download", to: "fdss_sync_manager#fdss_download", as: "fdss_download"


  # Defines the root path route ("/")
  root "home#index"

  # devise_for :users

  Rails.application.routes.draw do
  get 'fdss_api_keys/index'
    devise_for :users, controllers: {
      registrations: 'users/registrations'
    }
  end

  get "system_settings", to:"settings#system_settings", as: "system_settings"
  get "user_settings", to:"settings#user_settings", as:"user_settings"

  post "fdss_api_key_create", to: "fdss_api_keys#create", as: "fdss_api_key_create"
  post "fdss_api_key_destroy", to: "fdss_api_keys#destroy", as: "fdss_api_key_destroy"
  get "fdss_api_key_detail", to: "fdss_api_keys#detail", as: "fdss_api_key_detail"
end

app/views/layouts/_go_back.html.erb
<a href="javascript:history.back()" class="btn btn-primary"><img src="<%= asset_path("arrow_left_icon") %>" /> 返回</a>

app/views/layouts/_head_tabs.html.erb
<ul class="nav nav-tabs">
  <% @tabs.each_key  do |key| %>
    <% if @tab.to_s == key.to_s %>
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="<%= send(@path_method, { tab: key }) %>"><%= @tabs[key] %></a>
        </li>
    <% else %>
        <li class="nav-item">
          <a class="nav-link" href="<%= send(@path_method, { tab: key }) %>"><%= @tabs[key] %></a>
        </li>
    <% end %>

  <% end %>
</ul>

app/views/layouts/_upload_file.html.erb
<style>
    .upload-btn {
        position: fixed;
        bottom: 20px;
        right: 20px; /* 修改这里，将按钮移动到右下角 */
        left: auto;
        width: 80px;
        height: 80px;
        border-radius: 50%;
        background: linear-gradient(45deg, #52d1ee, #3072ff);
        box-shadow: 0 3px 6px rgba(0, 0, 0, 0.16), 0 3px 6px rgba(0, 0, 0, 0.23);
        color: white;
        text-align: center;
        line-height: 70px;
        font-size: 16px;
        font-weight: bold;
        cursor: pointer;
        z-index: 9999;
        transition: all 0.3s ease;
        border: none;
    }
    .upload-btn:hover {
        background: linear-gradient(45deg, #3072ff, #52d1ee);
        box-shadow: 0 10px 20px rgba(0, 0, 0, 0.19), 0 6px 6px rgba(0, 0, 0, 0.23);
        transform: translateY(-3px);
    }
</style>

<button class="upload-btn" href="#collapseExample" data-bs-toggle="offcanvas" data-bs-target="#offcanvasTop" aria-controls="offcanvasTop">
  上传文件
</button>


<% dir_paths = locals[:dir_path] %>
<% dir_path_str = locals[:dir_path_str] %>
<script>
  var dir_path = "<%= dir_path_str %>"
</script>


<div data-controller="upload-files" class="custom-parent-container" >
  <div class="offcanvas offcanvas-top" tabindex="-1" id="offcanvasTop" aria-labelledby="offcanvasTopLabel">
    <div class="offcanvas-body">
      <!-- 页面内容 -->
      <div class="container mt-5">
        <div id="upload_file_alert"></div>

        <h4>上传文件</h4>


        <nav aria-label="breadcrumb" style="--bs-breadcrumb-divider: '>'">
          <ol class="breadcrumb">
            <li class="breadcrumb-item active" aria-current="page">root</li>
            <% dir_paths.each do |path| %>
              <li class="breadcrumb-item active" aria-current="page"><%= path %></li>
            <% end %>
          </ol>
        </nav>


        <!-- 选择文件按钮 -->
        <div class="mb-3">
          <input type="file" class="form-control" id="fileInput" multiple>
        </div>

        <!-- 上传按钮 -->
        <button type="button" class="btn btn-primary" id="uploadBtn">上传</button>

        <!-- 文件列表 -->
        <ul class="list-group mt-3" id="fileList"></ul>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <link rel="icon" type="image/x-icon" href="<%= asset_path('fds_logo_dark.png') %>">
  <title>Fds</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  <%= javascript_include_tag 'libs/spark-md5.min' %>
  <%= javascript_include_tag 'jquery.min.js' %>
  <%= javascript_include_tag 'jquery_ujs.js' %>
  <%= javascript_importmap_tags %>

  <style>
      .custom-nav {
          background-color: #fff;
          box-shadow: 0px 0px 10px rgba(0, 0, 0, 0.3);
          width: 100%;
          position: fixed;
          top: 0;
          left: 0;
          z-index: 9999;
      }

     .custom-content {
         height: 100%; /* 设置固定高度以触发垂直滚动 */
         overflow-y: auto; /* 允许垂直滚动 */
         overflow-x: hidden; /* 禁用水平滚动 */

         /*background-color: #f7f7f7;*/
         padding: 0;
         padding-top: 60px;
         padding-bottom: 60px;
     }

     .custom-footer {
         position: fixed;
         bottom: 0;
         left: 0;
         width: 100%;
         text-align: center;
     }

  </style>

</head>

<header>

  <nav class="navbar navbar-expand-md custom-nav ">
    <div class="container-fluid">
      <div class="navbar-collapse" id="navbarNav">

        <div class="navbar-nav mr-auto">
          <a class="navbar-brand" href="<%= file_explore_path(dir: "/") %>">
            <img src="<%= asset_path('fds_logo_dark.png') %>" alt="Bootstrap" width="54" height="30">
          </a>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <div class="navbar-nav">
              <% if signed_in? %>
              <a class="nav-link active" aria-current="page" href="<%= file_explore_path(dir: "/") %>">主目录</a>
              <% end %>
            </div>
          </div>

        </div>



        <div class="navbar-nav mx-auto">

          <form class="d-flex" role="search">
            <% if signed_in? %>
            <input class="form-control me-2" type="search" placeholder="文件名" aria-label="Search" style="width: 300px">
            <button class="btn btn-dark" type="submit" style="width: 100px">搜索</button>
            <% end %>
          </form>

        </div>



        <div class="navbar-nav ml-auto">

          <% if user_signed_in? %>

            <div class="dropdown">
              <button class="btn btn-dark dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">
                <%= current_user.user_name %>
              </button>
              <ul class="dropdown-menu dropdown-menu-end">
<!--                <li><a class="dropdown-item" href="#">用户信息</a></li>-->
                <li><a class="dropdown-item" href="<%= file_explore_path(dir: "/") %>">回到主页</a></li>
                <li><a class="dropdown-item" href="<%= edit_user_registration_path %>">修改密码</a></li>
                <li><a class="dropdown-item" href="<%= user_settings_path %>">个人配置</a></li>
                <% if is_admin? %>
                  <li><a class="dropdown-item" href="<%= system_settings_path %>">系统管理</a></li>
                <% end %>
                <li><hr class="dropdown-divider"></li>
                <li>
                  <%= link_to "退出登录", destroy_user_session_path, :method => :delete, class: "dropdown-item"%>
                </li>
              </ul>
            </div>

          <% else %>
            <%= link_to "登录", new_session_path(resource_name), class: "btn btn-dark"%>
          <% end %>


        </div>
      </div>
    </div>
  </nav>

</header>

<body>
  <div class="custom-content">
    <div id="loadingOverlay" style="display: none;">
      <div id="loadingSpinner"></div>
    </div>
    <div class="container mt-5">
      <%= render_flash_messages %>
      <%= yield %>
    </div>
  </div>



  <footer class="bg-light text-center text-lg-start custom-footer">
    <div class="text-center p-2">
      &copy; 2024 Your Website. All rights reserved.
    </div>
  </footer>

</body>
</html>

<style>
    #loadingOverlay {
        position: fixed;
        top: 0;
        left: 0;
        width: 100%;
        height: 100%;
        background-color: rgba(252, 252, 252, 0);
        display: flex;
        justify-content: center;
        align-items: center;
        z-index: 9999;
    }

    #loadingSpinner {
        width: 40px;
        height: 40px;
        border: 4px solid #f3f3f3;
        border-top: 4px solid #3498db;
        border-radius: 50%;
        animation: spin 2s linear infinite;
    }

    @keyframes spin {
        0% {
            transform: rotate(0deg);
        }
        100% {
            transform: rotate(360deg);
        }
    }
</style>

<script>
    $(document).ready(function () {
        $(document).ajaxStart(function () {
            // 显示等待弹框
            $("#loadingOverlay").show();
        });

        $(document).ajaxStop(function () {
            // 隐藏等待弹框
            $("#loadingOverlay").hide();
        });
    })
</script>